# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Build python package
        run: |
          pip install -U setuptools
          make dist

      - name: Build Image
        run: docker build -t registry.digitalocean.com/aufdnb/krisa:staruha .

      - name: Install doctl                 # install the doctl on the runner
        uses: digitalocean/action-doctl@v2
        with:
            token: ${{ secrets.DOCKER_ACCESS_TOKEN}}

      # Runs a set of commands using the runners shell
      - name: Login into docker and push
        run: |
          doctl registry login
          docker push registry.digitalocean.com/aufdnb/krisa:staruha


      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 k8s-1-19-3-do-3-tor1-1611881652413

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f staruha-deployment.yaml

      - name: Verify deployment
        run: kubectl rollout status cronjob/staruha
